
/*1  for each director count the no of movies and tv shows created by them in separate columns 
for directors who have created tv shows and movies both */

SELECT ND.DIRECTOR,
COUNT(DISTINCT CASE WHEN N.TYPE='Movie' THEN N.SHOW_ID END) AS NO_OF_MOVIES,
COUNT(DISTINCT CASE WHEN N.TYPE='TV Show' THEN N.SHOW_ID END) AS NO_OF_TV_SHOW
FROM NETFLIX N
JOIN NETFLIX_DIRECTORS ND ON N.SHOW_ID=ND.SHOW_ID
GROUP BY ND.DIRECTOR
HAVING COUNT(DISTINCT N.TYPE) >1;

-- Having clause filters the grouped results (per director) to include only those directors who have worked on both Movies and TV Shows.

--2 which country has highest number of comedy movies 
-- -> NETFLIX_GENRE, NETFLIX_COUNTRY AND NETFLIX TABLE WOULD BE USED

SELECT * FROM NETFLIX_GENRE;

SELECT NC.COUNTRY, COUNT(DISTINCT NG.SHOW_ID) AS NO_OF_MOVIES
FROM NETFLIX_GENRE NG
INNER JOIN NETFLIX_COUNTRY NC ON NC.SHOW_ID=NG.SHOW_ID
INNER JOIN NETFLIX N ON N.SHOW_ID=NG.SHOW_ID
WHERE N.TYPE='Movie' AND NG.LISTED_IN='Comedies'
GROUP BY NC.COUNTRY
ORDER BY NO_OF_MOVIES DESC
LIMIT 1;

--3 for each year (as per date added to netflix), which director has maximum number of movies released

WITH CTE AS(
SELECT ND.DIRECTOR, EXTRACT(YEAR FROM DATE_ADDED) AS DATE_YEAR,  COUNT(N.SHOW_ID) AS NO_OF_MOVIES
FROM NETFLIX N
INNER JOIN NETFLIX_DIRECTORS ND ON N.SHOW_ID=ND.SHOW_ID
WHERE TYPE='Movie'
Group BY ND.DIRECTOR, DATE_YEAR
)
, CTE2 AS(
SELECT *,
ROW_NUMBER() OVER(PARTITION BY DATE_YEAR ORDER BY NO_OF_MOVIES DESC, DIRECTOR) AS RN
FROM CTE
)
SELECT * FROM CTE2 WHERE RN=1;

--4 what is average duration of movies in each genre

SELECT * FROM NETFLIX_GENRE;

SELECT NG.LISTED_IN AS GENRE, AVG(CAST(REGEXP_REPLACE(DURATION, '[^0-9]', '', 'g') AS INT)) AS AVG_DURATION
FROM NETFLIX N
JOIN NETFLIX_GENRE NG ON
N.SHOW_ID=NG.SHOW_ID
WHERE TYPE='Movie'
GROUP BY NG.LISTED_IN

--5  find the list of directors who have created horror and comedy movies both.
-- display director names along with number of comedy and horror movies directed by them 

-- TO FIND
-- 1. LIST OF DIRECTORS WHO HAVE CREATED HORROR AND COMEDY MOVIES BOTH
-- 2. DISPLAY DIRECTOR NAMES ALONG WITH NUMBER OF COMEDY AND HORROR MOVIES DIRECTED BY THEM

SELECT ND.DIRECTOR, 
COUNT(DISTINCT CASE WHEN NG.LISTED_IN='Comedies' THEN N.SHOW_ID END) AS NO_OF_COMEDY_MOVIES,
COUNT(DISTINCT CASE WHEN NG.LISTED_IN='Horror Movies' THEN N.SHOW_ID END) AS NO_OF_HORROR_MOVIES
FROM NETFLIX N
JOIN NETFLIX_GENRE NG ON N.SHOW_ID=NG.SHOW_ID
JOIN NETFLIX_DIRECTORS ND ON N.SHOW_ID=ND.SHOW_ID
WHERE TYPE='Movie' AND NG.LISTED_IN IN ('Comedies','Horror Movies')
GROUP BY ND.DIRECTOR
HAVING COUNT(DISTINCT NG.LISTED_IN)= 2;